Repository usaybia/srophe-eXist-app, pull requests merged in 2021-01, with the labels that each got.

#63 Added workflow to build and release Ant and Docker packages
  .github/release-drafter-dev.yml
  .github/release-drafter.yml
  .github/workflows/release-dev.yml
  .github/workflows/release.yml
  Dockerfile
  conf/conf.xml
  expath-pkg.xml
Labels: changelog: new app features

#64 Updated network visualizations on persons records to include nodes on relationship filters and relationship labels on edges
  d3xquery/js/vis.js
  expath-pkg.xml
Labels: changelog: visualization tweaks

#70 Integrated version number test into release workflow
  .github/release-drafter-dev.yml
  .github/release-drafter.yml
  .github/workflows/release-dev.yml
  .github/workflows/release.yml
Labels: changelog: new app features

#71 Fixed logic that allowed release worklow job to pass even if upload step was skipped #69
  .github/workflows/release-dev.yml
  .github/workflows/release.yml
Labels: changelog: bug fixes

#68 Updated Virtual Forum 2020 page to archive content
  forum2020/index.html
Labels: changelog: corrected content
